<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ESLLAP-3041" failures="3" tests="21" name="interviewPrep.TesngSeries.RetryTestDemo" time="0.031" errors="0" timestamp="04 Sep 2023 04:33:35 GMT" skipped="18">
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.001">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.001">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.011">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <failure message="expected to be true expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected to be true expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at interviewPrep.TesngSeries.RetryTestDemo.man2(RetryTestDemo.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.001">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.000">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="vi" time="0.001">
    <failure message="expected to be false expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected to be false expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at interviewPrep.TesngSeries.RetryTestDemo.vi(RetryTestDemo.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- vi -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.001">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.000">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.001">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.002">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.001">
    <skipped/>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.001">
    <failure message="expected to be false expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected to be false expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at interviewPrep.TesngSeries.RetryTestDemo.app(RetryTestDemo.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- app -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="man2" time="0.001">
    <skipped/>
  </testcase> <!-- man2 -->
  <testcase classname="interviewPrep.TesngSeries.RetryTestDemo" name="app" time="0.002">
    <skipped/>
  </testcase> <!-- app -->
</testsuite> <!-- interviewPrep.TesngSeries.RetryTestDemo -->
